Add JVM option Djava.endorsed.dirs to fix NoClassDefFoundError
Since Nexus3 version ~3.19, this JVM option is needed.
It will fix this errors that are flooding the logs during
nexus3 launch:

org.ops4j.pax.logging.pax-logging-api [Felix] ERROR : Bundle org.apache.felix.framework [0] EventDispatcher: Error during dispatch. (java.lang.NoClassDefFoundError: org/apache/karaf/specs/locator/OsgiLocator)

See: https://issues.sonatype.org/browse/NEXUS-21603